/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_printf_slog_Log */

#ifndef _Included_jp_printf_slog_Log
#define _Included_jp_printf_slog_Log
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_printf_slog_Log_DEBUG
#define jp_printf_slog_Log_DEBUG 0L
#undef jp_printf_slog_Log_INFO
#define jp_printf_slog_Log_INFO 1L
#undef jp_printf_slog_Log_WARN
#define jp_printf_slog_Log_WARN 2L
#undef jp_printf_slog_Log_ERROR
#define jp_printf_slog_Log_ERROR 3L
/*
 * Class:     jp_printf_slog_Log
 * Method:    setFileName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_printf_slog_Log_setFileName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_printf_slog_Log
 * Method:    setServiceAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_printf_slog_Log_setServiceAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_printf_slog_Log
 * Method:    enableOutput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jp_printf_slog_Log_enableOutput
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     jp_printf_slog_Log
 * Method:    stepIn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jp_printf_slog_Log_stepIn
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     jp_printf_slog_Log
 * Method:    stepOut
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_printf_slog_Log_stepOut
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_printf_slog_Log
 * Method:    message
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_jp_printf_slog_Log_message__ILjava_lang_String_2J
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     jp_printf_slog_Log
 * Method:    message
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_printf_slog_Log_message__ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
