/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_printf_WebSocketClient */

#ifndef _Included_jp_printf_WebSocketClient
#define _Included_jp_printf_WebSocketClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_printf_WebSocketClient
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_printf_WebSocketClient_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_printf_WebSocketClient
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_printf_WebSocketClient_close
  (JNIEnv *, jobject);

/*
 * Class:     jp_printf_WebSocketClient
 * Method:    send
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_printf_WebSocketClient_send__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_printf_WebSocketClient
 * Method:    send
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_jp_printf_WebSocketClient_send__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
